### PR TITLE
Publish kafka as an (un)chart

### PR DESCRIPTION
**Pull request by scothis**
We don't want to support a kafka install as part of riff, yet we need
kafka for our own tests. This chart/unchart is intended to fill that gap
but is not intended for end-users.

### CODE REVIEW

**Comment by jldec** [comment]
nice - thanks for adding this @scothis.

**Comment by trisberg** [comment]
Should we name the kafka service `kafkabroker` to be more consistent with [docs](https://projectriff.io/docs/v0.5/runtimes/streaming#kafkaprovider)? Assuming we would connect to `kafka.kafka` with what we have now vs `kafkabroker.kafka` if we change the service name.

**Comment by scothis** [comment]
@trisberg I don't want to do more surgery than necessary on the chart. There may be some other resource in the chart down the road that expects that name to be in a consistent form.

**Comment by trisberg** [comment]
> @trisberg I don't want to do more surgery than necessary on the chart. There may be some other resource in the chart down the road that expects that name to be in a consistent form.

Shouldn't be since that is the release name specified by the end user

**Comment by scothis** [comment]
> Shouldn't be since that is the release name specified by the end user

That would be `{releaseName}-kafka`, still not `kafkabroker`.

**Pull request merged**
